server:
  port: 8080
spring:
  application:
    name: exam-user #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/exam?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Yuanyulou789!
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  redis:
    host: 114.67.72.37
    port: 6379
    password: redis123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置dao接口与sql语句映射的xml文件的类路径地址，**注意不需要加classpath**
  mapper-locations: /mapper/*/*.xml
  type-aliases-package : com.keyou.domain.basicQuery